# Generated by Django 4.2.10 on 2024-03-29 04:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FG_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=55)),
                ('Item_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number (e.g., 12ABCDE1234F1Z1).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$')])),
                ('location', models.CharField(max_length=255)),
                ('company_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RM_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number (e.g., 12ABCDE1234F1Z1).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$')])),
                ('location', models.CharField(max_length=255)),
                ('company_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WastageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WI_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('position', models.CharField(default='HR_Manager', max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrate_date', models.DateTimeField()),
                ('RM_qty', models.IntegerField(default=2)),
                ('WI_qty', models.IntegerField(default=0)),
                ('FG_qty', models.IntegerField(default=1)),
                ('FG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.finishgoods')),
                ('RM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterial')),
                ('WI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.wastageitem')),
            ],
        ),
    ]
