# Generated by Django 4.2.10 on 2024-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_report',
            name='FG',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='FG_qty',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='RM',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='RM_qty',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='WI',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='WI_qty',
        ),
        migrations.CreateModel(
            name='Production_RM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RM_qty', models.IntegerField()),
                ('RM_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.rawmaterial')),
                ('production_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.production_report')),
            ],
        ),
        migrations.CreateModel(
            name='Production_FG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FG_qty', models.IntegerField()),
                ('FG_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.finishgoods')),
                ('production_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.production_report')),
            ],
        ),
    ]
